title: My awesome title
author: Pichtou
theme: minima
email: aalixrita@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  Its ablog for test so i can't have a lot expectation about de final issue 

# social links
twitter_username: no twitter
github_username:  Pichtou

show_excerpts: true # set to false to remove excerpts on the homepage
